### ISSUE TITLE
Markers appear fuzzy

### ISSUE THREAD

**Issue by IvanSanchez** [fnicollet/Leaflet#8] opened 2016-09-27 14:00 UTC
The markers appear fuzzy, probably to some non-integer offset when transforming them.

There should be some way to make markers keep integer offsets when transforming, altough this is probably not very easy to do without taking them out of the `rotatePane` and recalculating their positions on every bearing change.

**Comment by fnicollet** [comment] 2016-09-27 14:03
Custom markers? The blue default markers of the simple example looks fine
to me?

**Comment by IvanSanchez** [comment] 2016-09-27 14:03
Nah, they become blurry, at least on firefox, due to sub-pixel sampling or something. The problem disappears when the bearing is set at zero.

**Comment by IvanSanchez** [comment] 2016-09-27 14:07
![screenshot_20160927_160452](https://cloud.githubusercontent.com/assets/1125786/18877110/68066e26-84cc-11e6-9aca-4b7329b23692.png)
![screenshot_20160927_160452-zoomed](https://cloud.githubusercontent.com/assets/1125786/18877109/67f854b2-84cc-11e6-9aa5-5bca6e1c3557.png)

Nah, they become blurry, at least on firefox, due to sub-pixel sampling or something. The problem disappears when the bearing is set at zero.

Probably the browser is rotating the marker images twice, introducing some quality loss. The goal should be to rotate them _zero_ times.

**Comment by fnicollet** [comment] 2016-09-27 14:21
Thanks, cannot reproduce on Chrome, so that must be related to the
rendering engine being different in FF, probably the subpixel issue that
you know well :)

I'll try in FF with integer offset, see if that solve the issue but i am
afraid it would be from the parent container being rotated. Your suggestion
is to get the out of the rotatePane and place them in an absolute way?

**Comment by fnicollet** [comment] 2017-04-01 17:14
Closed now that #21 has been merged, which fix the issue by not rotating the markers

**Closed as completed by fnicollet** 2017-04-01 17:14 UTC
